apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monoceros-best-static-html
  namespace: httpd
spec:
  interval: 5m
  chart:
    spec:
      chart: static-html
      version: '0.2.0'
      sourceRef:
        kind: HelmRepository
        name: pixil98
        namespace: flux-system
      interval: 1h0m0s
  values:
    gitRepo: git@github.com:pixil98/monoceros-best-html.git
    deploykey: monoceros-best-deploy-key
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - monoceros.best
        - www.monoceros.best
