apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-typesense
  namespace: photos
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: typesense
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: typesense
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: typesense
        app.kubernetes.io/instance: immich
    spec:
      #serviceAccountName: default
      #automountServiceAccountToken: true
      #dnsPolicy: ClusterFirst
      #enableServiceLinks: true
      containers:
        - name: immich-typesense
          image: registry.lab.reisman.org/proxy.docker.io/typesense/typesense:0.24.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_HOSTNAME
              value: immich-postgresql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets 
                  key: postgresql-user-password
                  optional: false
            - name: DB_USERNAME
              value: immich
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning:3003
            - name: IMMICH_SERVER_URL
              value: http://immich-server:3001
            - name: IMMICH_WEB_URL
              value: http://immich-web:3000
            - name: REDIS_HOSTNAME
              value: immich-redis-master
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: immich-secrets 
                  key: typesense-api-key
                  optional: false
            - name: TYPESENSE_DATA_DIR
              value: /tsdata
            - name: TYPESENSE_ENABLED
              value: "true"
            - name: TYPESENSE_HOST
              value: immich-typesense
          ports:
            - name: http
              containerPort: 8108
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /tsdata
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-typesense-data

