apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-typesense-data
  namespace: photos
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
