apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-postgresql
  namespace: photos
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnamicharts/postgresql
      version: '>=12.4.2 <13.0.0'
      sourceRef:
        kind: HelmRepository
        name: registry-lab
        namespace: flux-system
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
      storageClass: nfs-client
    architecture: standalone
    primary:
      livenessProbe:
        initialDelaySeconds: 120
    auth:
      database: immich
      username: immich
      existingSecret: immich-secrets
      secretKeys:
        adminPasswordKey: postgresql-admin-password
        userPasswordKey: postgresql-user-password
      usePasswordFiles: true
