apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: photos
spec:
  #TODO: back this up??
  storageClassName: "nfs-client-nobackup"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload
  namespace: photos
spec:
  #TODO: back this up??
  storageClassName: "nfs-client-nobackup"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-encoded-video
  namespace: photos
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-profile
  namespace: photos
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-thumbs
  namespace: photos
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi