apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-encoded-video
  namespace: photos
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-profile
  namespace: photos
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-thumbs
  namespace: photos
spec:
  storageClassName: nfs-client-nobackup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi