apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnamicharts/postgresql
      version: '>=12.4.2 <13.0.0'
      sourceRef:
        kind: HelmRepository
        name: registry-lab
        namespace: flux-system
  values:
    global:
      imageRegistry: registry.lab.reisman.org/proxy.docker.io
      storageClass: nfs-client-nobackup
    architecture: standalone
    auth:
      database: authentik
      existingSecret: postgresql-auth
      adminPasswordKey: postgres-password
      userPasswordKey: password
      username: authentik
