apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - wikijs_postgresql.yaml
  - wikijs_env.yaml
  - wikijs_deployment.yaml
  - wikijs_service.yaml
  - wikijs_ingress.yaml
  - wikijs_vpa.yaml
