apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-mariadb-data
  namespace: wiki
spec:
  storageClassName: truenas-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
