apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wiki
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-core-10-infrastructure-configs
  interval: 10m
  path: ./manifests/wiki
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-values
      - kind: Secret
        name: flux-secrets
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
  wait: true
  # The bootstrap Job is immutable; recreate it when its spec changes.
  force: true
