apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-groups
  namespace: cloud
  labels:
    app.kubernetes.io/name: groups
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: groups
      app.kubernetes.io/instance: ocis
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: groups
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: groups
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["groups", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: MICRO_REGISTRY_ADDRESS
              value: ""

            - name: OCIS_LOG_LEVEL
              value: "info"
            - name: OCIS_LOG_PRETTY
              value: "false"
            - name: OCIS_LOG_COLOR
              value: "false"

            - name: GROUPS_GRPC_ADDR
              value: 0.0.0.0:9160
            - name: GROUPS_DEBUG_ADDR
              value: 0.0.0.0:9161

            - name: OCIS_LDAP_INSECURE
              value: "true"
            - name: OCIS_LDAP_USER_BASE_DN
              value: "ou=users,o=libregraph-idm"
            - name: OCIS_LDAP_GROUP_BASE_DN
              value: "ou=groups,o=libregraph-idm"
            - name: OCIS_LDAP_USER_SCOPE
              value: "sub"
            - name: OCIS_LDAP_GROUP_SCOPE
              value: "sub"

            - name: OCIS_LDAP_URI
              value: "ldaps://ocis-idm:9235"
            - name: OCIS_LDAP_CACERT
              value: "" # no cert needed
            - name: OCIS_LDAP_BIND_DN
              value: "uid=reva,ou=sysusers,o=libregraph-idm"
            - name: GROUPS_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: idm-reva-password
            - name: OCIS_OIDC_ISSUER
              value: "https://auth.dev.lab.reisman.org/application/o/owncloud/"
            - name: OCIS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: jwt-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: grpc
              containerPort: 9160
            - name: metrics-debug
              containerPort: 9161
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: ocis-config-tmp
          emptyDir: {}
        - name: ldap-ca
          emptyDir: {}
