apiVersion: v1
kind: ConfigMap
metadata:
  name: ocis-server-config
  namespace: cloud
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: ocis
data:
  ocis.yaml: |
    proxy:
      role_assignment:
        oidc_role_mapper:
          role_mapping:
          - role_name: admin
            claim_value: cloud-admins
          - role_name: user
            claim_value: cloud-users
          - role_name: guest
            claim_value: cloud-guests