apiVersion: v1
kind: Service
metadata:
  name: ocis-server
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: metrics-debug
      port: 9205
      protocol: TCP
