apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: store
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: store
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9460
      protocol: TCP
    - name: metrics-debug
      port: 9464
      protocol: TCP
