apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ocis-redis
  namespace: cloud
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnamicharts/redis
      version: '>=17.0.0 <18.0.0'
      sourceRef:
        kind: HelmRepository
        name: registry-lab
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      existingSecret: ocis-secrets
      existingSecretPasswordKey: redis-password 
    image:
      registry: registry.lab.reisman.org/proxy.docker.io
    master:
      #TODO: enable persistence
      persistence:
        enabled: false
        storageClass: nfs-client-nobackup
