apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-userlog
  namespace: cloud
  labels:
    app.kubernetes.io/name: userlog
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: userlog
      app.kubernetes.io/instance: ocis
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: userlog
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: userlog
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["userlog", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: MICRO_REGISTRY_ADDRESS
              value: ""

            - name: OCIS_LOG_LEVEL
              value: "info"
            - name: OCIS_LOG_PRETTY
              value: "false"
            - name: OCIS_LOG_COLOR
              value: "false"

            - name: USERLOG_HTTP_ADDR
              value: 0.0.0.0:8080
            - name: USERLOG_DEBUG_ADDR
              value: 0.0.0.0:9210

            - name: OCIS_PERSISTENT_STORE
              value: "redis"
            - name: OCIS_PERSISTENT_STORE_NODES
              value: "ocis-redis-master:6379"
            - name: OCIS_EVENTS_ENDPOINT
              value: ocis-nats:9233
            - name: OCIS_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: machine-auth-api-key
            - name: OCIS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: jwt-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: http
              containerPort: 8080
            - name: metrics-debug
              containerPort: 9210
          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true
      volumes:
        - name: ocis-config-tmp
          emptyDir: {}
        - name: messaging-system-ca
          emptyDir: {}
