apiVersion: v1
kind: Service
metadata:
  name: ocis-search
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: search
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: search
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9220
      protocol: TCP
    - name: metrics-debug
      port: 9224
      protocol: TCP
