apiVersion: v1
kind: Service
metadata:
  name: ocs
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: ocs
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: ocs
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: http
      port: 9110
      protocol: TCP
    - name: metrics-debug
      port: 9114
      protocol: TCP
