#TODO: generate proper values and seal this
apiVersion: v1
kind: Secret
metadata:
  name: ocis-secrets
  namespace: cloud
data:
  redis-password: dGhpc2lzYWJhZHBhc3N3b3Jk
  machine-auth-api-key: "blE2b01IOVZZNkdkVFVZcVNtS1FkTFZUMnMyQU00"
  jwt-secret: "eDIweFhLTDBBRDVDMUpjMFFWdUxlUzZhYlRuWjA3"
  api-key: "TjNnNkdSTTduU1dXbWJ0VEdZMFl2OEtLRHlkZ3FF"
  transfer-secret: "S1FidW5HbnVmUmxYTEhGaFlxdnJ4TVNJYUhxcWVI"
  thumbnails-transfer-secret: "aktQNXQwYlozUjBTc2lEZ2ppZGxncHhMZDVta29t"
  idm-admin-password: dGhpc2lzYWJhZHBhc3N3b3Jk
  idm-svc-password: dGhpc2lzYWJhZHBhc3N3b3Jk
  idm-reva-password: dGhpc2lzYWJhZHBhc3N3b3Jk
  idm-idp-password: dGhpc2lzYWJhZHBhc3N3b3Jk
