apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-store
  namespace: cloud
  labels:
    app.kubernetes.io/name: store
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: store
      app.kubernetes.io/instance: ocis
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/113
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: store
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: store
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["store", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: MICRO_REGISTRY_ADDRESS
              value: ""

            - name: OCIS_LOG_LEVEL
              value: "info"
            - name: OCIS_LOG_PRETTY
              value: "false"
            - name: OCIS_LOG_COLOR
              value: "false"

            - name: STORE_GRPC_ADDR
              value: 0.0.0.0:9460
            - name: STORE_DEBUG_ADDR
              value: 0.0.0.0:9464
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: grpc
              containerPort: 9460
            - name: metrics-debug
              containerPort: 9464
          volumeMounts:
            - name: store-data
              mountPath: /var/lib/ocis
      volumes:
        - name: store-data
          emptyDir: {}
