apiVersion: v1
kind: Service
metadata:
  name: ocis-users
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9144
      protocol: TCP
    - name: metrics-debug
      port: 9145
      protocol: TCP
