apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-authmachine
  namespace: cloud
  labels:
    app.kubernetes.io/name: authmachine
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authmachine
      app.kubernetes.io/instance: ocis
  replicas: 1
  
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authmachine
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: authmachine
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["auth-machine", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: MICRO_REGISTRY_ADDRESS
              value: ""

            - name: OCIS_LOG_LEVEL
              value: "debug"
            - name: OCIS_LOG_PRETTY
              value: "true"
            - name: OCIS_LOG_COLOR
              value: "true"

            - name: AUTH_MACHINE_GRPC_ADDR
              value: 0.0.0.0:9166
            - name: AUTH_MACHINE_DEBUG_ADDR
              value: 0.0.0.0:9167

            - name: OCIS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: jwt-secret
            - name: OCIS_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: machine-auth-api-key
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: grpc
              containerPort: 9166
            - name: metrics-debug
              containerPort: 9167
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
