apiVersion: v1
kind: Service
metadata:
  name: ocis-settings
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: settings
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: settings
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9191
      protocol: TCP
    - name: http
      port: 9190
      protocol: TCP
    - name: metrics-debug
      port: 9194
      protocol: TCP
