apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-idm
  namespace: cloud
  labels:
    app.kubernetes.io/name: idm
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: idm
      app.kubernetes.io/instance: ocis
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: idm
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: idm
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["idm", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            # logging
            - name: OCIS_LOG_LEVEL
              value: "info"
            - name: OCIS_LOG_PRETTY
              value: "false"
            - name: OCIS_LOG_COLOR
              value: "false"
            # debug
            - name: IDM_DEBUG_ADDR
              value: "127.0.0.1:9239"
            # ldap
            - name: IDM_LDAPS_ADDR
              value: "127.0.0.1:9235"
            # idm
            - name: IDM_CREATE_DEMO_USERS
              value: "false"
            - name: IDM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: idm-admin-password
            - name: IDM_SVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: idm-svc-password
            - name: IDM_REVASVC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: idm-reva-password
            - name: OCIS_ADMIN_USER_ID
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: admin-user-id
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: ldaps
              containerPort: 9235
            - name: metrics-debug
              containerPort: 9239
          volumeMounts:
            - name: idm-data
              mountPath: /var/lib/ocis
      volumes:
        - name: idm-data
          emptyDir: {}
