apiVersion: v1
kind: Service
metadata:
  name: ocis-graph
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: graph
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: graph
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: http
      port: 9120
      protocol: TCP
    - name: metrics-debug
      port: 9124
      protocol: TCP
