apiVersion: v1
kind: Service
metadata:
  name: ocis-ocdav
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: ocdav
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: ocdav
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: metrics-debug
      port: 9163
      protocol: TCP
