apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-gateway
  namespace: cloud
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/instance: ocis
  replicas: 1
  
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: gateway
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["gateway", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: MICRO_REGISTRY_ADDRESS
              value: ""

            - name: OCIS_LOG_LEVEL
              value: "info"
            - name: OCIS_LOG_PRETTY
              value: "false"
            - name: OCIS_LOG_COLOR
              value: "false"

            - name: GATEWAY_GRPC_ADDR
              value: 0.0.0.0:9142
            - name: GATEWAY_DEBUG_ADDR
              value: 0.0.0.0:9143

            - name: OCIS_URL
              value: "https://cloud.dev.lab.reisman.org"

            # create home cache defaults to memory so we don't put too much load on our shared cache
            - name: GATEWAY_CREATE_HOME_CACHE_STORE
              value: memory
            - name: GATEWAY_STORAGE_USERS_MOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: "ocis-storage-users"
                  key: storage-uuid

            - name: OCIS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: jwt-secret
            - name: OCIS_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: transfer-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: grpc
              containerPort: 9142
            - name: metrics-debug
              containerPort: 9143
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
