apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-storagepubliclink
  namespace: cloud
  labels:
    app.kubernetes.io/name: storagepubliclink
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storagepubliclink
      app.kubernetes.io/instance: ocis
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: storagepubliclink
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: storagepubliclink
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["storage-publiclink", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: MICRO_REGISTRY_ADDRESS
              value: ""
            - name: STORAGE_PUBLICLINK_LOG_COLOR
              value: "false"
            - name: STORAGE_PUBLICLINK_LOG_LEVEL
              value: "info"
            - name: STORAGE_PUBLICLINK_LOG_PRETTY
              value: "false"
            - name: STORAGE_PUBLICLINK_TRACING_ENABLED
              value: "false"
            - name: STORAGE_PUBLICLINK_TRACING_TYPE
              value: "jaeger"
            - name: STORAGE_PUBLICLINK_TRACING_ENDPOINT
              value: ""
            - name: STORAGE_PUBLICLINK_TRACING_COLLECTOR
              value: ""
            - name: STORAGE_PUBLICLINK_DEBUG_PPROF
              value: "false"
            - name: STORAGE_PUBLICLINK_GRPC_ADDR
              value: 0.0.0.0:9178
            - name: STORAGE_PUBLICLINK_DEBUG_ADDR
              value: 0.0.0.0:9179
            - name: STORAGE_PUBLICLINK_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: jwt-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: grpc
              containerPort: 9178
            - name: metrics-debug
              containerPort: 9179
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
