apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-search
  namespace: cloud
  labels:
    app.kubernetes.io/name: search
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: search
      app.kubernetes.io/instance: ocis
  replicas: 1 #TODO: https://github.com/owncloud/ocis-charts/issues/15
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: search
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: search
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["search", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: MICRO_REGISTRY_ADDRESS
              value: ""
            - name: SEARCH_LOG_COLOR
              value: "false"
            - name: SEARCH_LOG_LEVEL
              value: "info"
            - name: SEARCH_LOG_PRETTY
              value: "false"
            - name: SEARCH_DEBUG_PPROF
              value: "false"
            - name: SEARCH_GRPC_ADDR
              value: 0.0.0.0:9220
            - name: SEARCH_DEBUG_ADDR
              value: 0.0.0.0:9224
            - name: SEARCH_EVENTS_ENDPOINT
              value: ocis-nats:9233
            - name: SEARCH_EXTRACTOR_TYPE
              value: basic
            - name: SEARCH_EXTRACTOR_CS3SOURCE_INSECURE
              value: "false"
            - name: SEARCH_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: machine-auth-api-key
            - name: OCIS_ASYNC_UPLOADS
              value: "true"
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: grpc
              containerPort: 9220
            - name: metrics-debug
              containerPort: 9224
          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true
            - name: search-data
              mountPath: /var/lib/ocis
      volumes:
        - name: ocis-config-tmp
          emptyDir: {}
        - name: messaging-system-ca
          emptyDir: {}
        - name: search-data
          emptyDir: {}
