apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-settings
  namespace: cloud
  labels:
    app.kubernetes.io/name: settings
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: settings
      app.kubernetes.io/instance: ocis
  replicas: 1
  
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: settings
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: settings
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["settings", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: MICRO_REGISTRY_ADDRESS
              value: ""
            - name: SETTINGS_LOG_COLOR
              value: "false"
            - name: SETTINGS_LOG_LEVEL
              value: "info"
            - name: SETTINGS_LOG_PRETTY
              value: "false"
            - name: SETTINGS_TRACING_ENABLED
              value: "false"
            - name: SETTINGS_TRACING_TYPE
              value: "jaeger"
            - name: SETTINGS_TRACING_ENDPOINT
              value: ""
            - name: SETTINGS_TRACING_COLLECTOR
              value: ""
            - name: SETTINGS_DEBUG_PPROF
              value: "false"
            - name: SETTINGS_HTTP_ADDR
              value: 0.0.0.0:9190
            - name: SETTINGS_GRPC_ADDR
              value: 0.0.0.0:9191
            - name: SETTINGS_DEBUG_ADDR
              value: 0.0.0.0:9194
            - name: SETTINGS_ADMIN_USER_ID
              value: ""
            - name: SETTINGS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: jwt-secret
            - name: OCIS_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: api-key
            - name: OCIS_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: "ocis-secrets"
                  key: user-id
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: http
              containerPort: 9190
            - name: grpc
              containerPort: 9191
            - name: metrics-debug
              containerPort: 9194
