apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: routing
  namespace: envoy-gateway-system
spec:
  mergeGateways: true
  provider:
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        loadBalancerIP: "${vals_infra_envoyGateway_loadBalancerIP}"
    type: Kubernetes
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: routing
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: routing
    namespace: envoy-gateway-system
