apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - plex_deployment.yaml
  - plex_claims.yaml
  - plex_service.yaml
  - libation_job.yaml
  - libation_accounts.yaml
  - libation_claims.yaml

configMapGenerator:
  - name: libation-settings
    namespace: plex
    files:
      - libation_config/Settings.json