apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: docker.io/plexinc/pms-docker:1.42.2.10156-f737b826c
          imagePullPolicy: IfNotPresent
          ports:
            - name: plex
              containerPort: 32400
          env:
            - name: HOSTNAME
              value: "plex.reisman.org"
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /data/audiobooks
              name: audiobooks
            - mountPath: /data/audible
              name: audible
            - mountPath: /data/tv
              name: tv
            - mountPath: /data/music
              name: music
            - mountPath: /data/movies
              name: movies
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: config-pvc
        - name: audiobooks
          nfs:
            server: 192.168.1.10
            path: /mnt/main/media/audiobooks
            readOnly: true
        - name: audible
          nfs:
            server: 192.168.1.10
            path: /mnt/main/media/audible
            readOnly: true
        - name: tv
          nfs:
            server: 192.168.1.10
            path: /mnt/main/media/tv
            readOnly: true
        - name: music
          nfs:
            server: 192.168.1.10
            path: /mnt/main/media/music
            readOnly: true
        - name: movies
          nfs:
            server: 192.168.1.10
            path: /mnt/main/media/movies
            readOnly: true
