apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: plex
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
