apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubesync-config
  namespace: plex
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
