apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: mapper-server-vpa
  namespace: mapper
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: mapper-server
  updatePolicy:
    updateMode: "Off"
