apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapper-server-db
  namespace: mapper
spec:
  storageClassName: truenas-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
