apiVersion: v1
kind: Secret
metadata:
  name: volsync-restic
  namespace: mapper
type: Opaque
stringData:
  RESTIC_REPOSITORY: "s3:${vals_infra_storage_backup_s3Endpoint}/${vals_info_cluster_name}/mapper-server-db"
  RESTIC_PASSWORD: "${secrets_infra_storage_backup_resticPassword}"
  AWS_ACCESS_KEY_ID: "${secrets_infra_storage_backup_awsAccessKeyId}"
  AWS_SECRET_ACCESS_KEY: "${secrets_infra_storage_backup_awsSecretAccessKey}"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mapper-server-db-backup
  namespace: mapper
spec:
  paused: ${vals_infra_storage_backup_paused}
  sourcePVC: mapper-server-db
  trigger:
    schedule: "0 2 * * *"
  restic:
    pruneIntervalDays: 14
    repository: volsync-restic
    volumeSnapshotClassName: truenas-iscsi
    copyMethod: Snapshot
    storageClassName: truenas-iscsi-ephemeral
    cacheStorageClassName: truenas-iscsi-ephemeral
    retain:
      daily: 7
      weekly: 4
      monthly: 3
