apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-ir3
  namespace: games
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
