apiVersion: v1
kind: Service
metadata:
  name: necesse
  namespace: games
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.16
  selector:
    app: necesse
  ports:
    - port: 14159
      targetPort: 14159
      protocol: UDP
