apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-paperless-consume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  claimRef:
    name: consume
    namespace: paperless
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-paperless-consume  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//192.168.1.10/files/PaperlessConsume"
    #nodeStageSecretRef:
    #  name: smbcreds
    #  namespace: default