apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 1h
  ref:
    tag: v1.8.3
  url: oci://docker.io/envoyproxy/gateway-helm
