apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: aaron@reisman.org
    privateKeySecretRef:
      name: letsencrypt-production-dns
    solvers:
    - dns01:
        rfc2136:
          nameserver: ns1.reisman.org
          tsigKeyName: letsencrypt-dev
          tsigAlgorithm: HMACSHA512
          tsigSecretSecretRef:
            name: letsencrypt-dev-tsig
            key: key