apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik-remote-cluster
  namespace: auth
  labels:
    app.kubernetes.io/name: remote-cluster
    app.kubernetes.io/instance: authentik
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: authentik-remote-cluster
  namespace: auth
  labels:
    app.kubernetes.io/name: remote-cluster
    app.kubernetes.io/instance: authentik
  annotations:
    kubernetes.io/service-account.name: authentik-remote-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authentik-remote-cluster
  namespace: auth
  labels:
    app.kubernetes.io/name: remote-cluster
    app.kubernetes.io/instance: authentik
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - configmaps
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - middlewares
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
      - delete
      - list
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-remote-cluster
  namespace: auth
  labels:
    app.kubernetes.io/name: remote-cluster
    app.kubernetes.io/instance: authentik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authentik-remote-cluster
subjects:
  - kind: ServiceAccount
    name: authentik-remote-cluster
    namespace: default