apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-release
  namespace: flux-system
spec:
  interval: 5m
  path: "./flux/infrastructure/metallb/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: metallb-release
  path: "./flux/infrastructure/metallb/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
