apiVersion: v1
kind: Service
metadata:
  name: ocis-webdav
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: webdav
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: http
      port: 9115
      protocol: TCP
    - name: metrics-debug
      port: 9119
      protocol: TCP
