apiVersion: v1
kind: Service
metadata:
  name: ocis-frontend
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: http
      port: 9140
      protocol: TCP
    - name: metrics-debug
      port: 9141
      protocol: TCP
