apiVersion: v1
kind: Service
metadata:
  name: ocis-gateway
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9142
      protocol: TCP
    - name: metrics-debug
      port: 9143
      protocol: TCP
