apiVersion: v1
kind: Service
metadata:
  name: ocis-web
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: http
      port: 9100
      protocol: TCP
    - name: metrics-debug
      port: 9104
      protocol: TCP
