apiVersion: v1
kind: Service
metadata:
  name: ocis-storagepubliclink
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: storagepubliclink
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: storagepubliclink
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9178
      protocol: TCP
    - name: metrics-debug
      port: 9179
      protocol: TCP
