apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-eventhistory
  namespace: cloud
  labels:
    app.kubernetes.io/name: eventhistory
    app.kubernetes.io/instance: ocis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: eventhistory
      app.kubernetes.io/instance: ocis
  replicas: 1
  
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eventhistory
        app.kubernetes.io/instance: ocis
    spec:
      automountServiceAccountToken: true
      
      securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: eventhistory
          image: "registry.lab.reisman.org/proxy.docker.io/owncloud/ocis:3.1.0-next.2"
          imagePullPolicy: IfNotPresent
          command: ["ocis"]
          args: ["eventhistory", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: MICRO_REGISTRY_ADDRESS
              value: ""

            - name: OCIS_LOG_LEVEL
              value: "debug"
            - name: OCIS_LOG_PRETTY
              value: "true"
            - name: OCIS_LOG_COLOR
              value: "true"

            - name: EVENTHISTORY_GRPC_ADDR
              value: 0.0.0.0:8080
            - name: EVENTHISTORY_DEBUG_ADDR
              value: 0.0.0.0:9270

            - name: OCIS_PERSISTENT_STORE
              value: "redis"
            - name: OCIS_PERSISTENT_STORE_NODES
              value: "ocis-redis-master:6379"
            - name: OCIS_EVENTS_ENDPOINT
              value: ocis-nats:9233
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources: {}
          ports:
            - name: grpc
              containerPort: 8080
            - name: metrics-debug
              containerPort: 9270
          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true
      volumes:
        - name: ocis-config-tmp
          emptyDir: {}
        - name: messaging-system-ca
          emptyDir: {}