apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-storagesystem-data
  namespace: cloud
  labels:
    app.kubernetes.io/name: storagesystem
    app.kubernetes.io/instance: ocis
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "5Gi"