apiVersion: v1
kind: Service
metadata:
  name: ocis-appregistry
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: appregistry
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: appregistry
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9242
      protocol: TCP
    - name: metrics-debug
      port: 9243
      protocol: TCP
