apiVersion: v1
kind: Service
metadata:
  name: ocis-authmachine
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: authmachine
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: authmachine
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9166
      protocol: TCP
    - name: metrics-debug
      port: 9167
      protocol: TCP
