apiVersion: v1
kind: Service
metadata:
  name: ocis-storagesystem
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: storagesystem
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: storagesystem
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9215
      protocol: TCP
    - name: http
      port: 9216
      protocol: TCP
    - name: metrics-debug
      port: 9217
      protocol: TCP
