apiVersion: v1
kind: Service
metadata:
  name: ocis-eventhistory
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: eventhistory
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: eventhistory
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
    - name: metrics-debug
      port: 9270
      protocol: TCP
