apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocis-service-registry
  namespace: cloud
  labels:
    app.kubernetes.io/name: ocis
    app.kubernetes.io/instance: ocis
rules:
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - pods
  verbs:
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocis-service-registry
  namespace: cloud
  labels:
    app.kubernetes.io/name: ocis
    app.kubernetes.io/instance: ocis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocis-service-registry
subjects:
- kind: ServiceAccount
  name: default
  namespace: cloud
