apiVersion: v1
kind: Service
metadata:
  name: ocis-storageusers
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: storageusers
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: storageusers
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9157
      protocol: TCP
    - name: http
      port: 9158
      protocol: TCP
    - name: metrics-debug
      port: 9159
      protocol: TCP
