apiVersion: v1
kind: Service
metadata:
  name: ocis-sharing
  namespace: cloud
  labels:
    ocis-metrics: enabled
    app.kubernetes.io/name: sharing
    app.kubernetes.io/instance: ocis
spec:
  selector:
    app.kubernetes.io/name: sharing
    app.kubernetes.io/instance: ocis
  type: ClusterIP
  ports:
    - name: grpc
      port: 9150
      protocol: TCP
    - name: metrics-debug
      port: 9151
      protocol: TCP
