apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amavis-virusmails
  namespace: mail
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
