apiVersion: apps/v1
kind: Deployment
metadata:
  name: amavis
  namespace: mail
spec:
  selector:
    matchLabels:
      app: mailserver
      tier: amavis
  template:
    metadata:
      labels:
        app: mailserver
        tier: amavis
        logType: amavis
    spec:
      containers:
      - name: amavis
        image: technicalguru/mailserver-amavis:2.11.1.4
        imagePullPolicy: IfNotPresent
        env:
        - name: AV_MYDOMAIN
          value: "reisman.org"
        - name: AV_POSTFIX_SERVICE_NAME
          value: "postfix-internal"
        - name: AV_POSTFIX_SERVICE_PORT
          value: "10025"
        - name: AV_VIRUSADMIN_EMAIL
          value: "postmaster"
        - name: AV_NOTIFY_SENDER
          value: "postmaster"
        - name: AV_NOTIFY_ADMIN
          value: "postmaster"
        ports:
        - containerPort: 10024
          name: amavis
        volumeMounts:
        - name: virusmails
          mountPath: /var/virusmails
      volumes:
        - name: virusmails
          persistentVolumeClaim:
            claimName: amavis-virusmails
