apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot-nfs-config
  namespace: mail
data:
  00-nfs.conf: |
    mail_nfs_index = no
    mail_nfs_storage = no
    mail_fsync = always
    mmap_disable = yes
    