apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendkim
  namespace: mail
spec:
  selector:
    matchLabels:
      app: mailserver
      tier: opendkim
  template:
    metadata:
      labels:
        app: mailserver
        tier: opendkim
        logType: opendkim
    spec:
      containers:
      - name: opendkim
        image: technicalguru/mailserver-opendkim:2.11.0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: DKIM_DOMAIN
          value: "reisman.org"
        - name: DKIM_PORT
          value: "41001"
        - name: DKIM_DB_HOST
          value: "mariadb"
        - name: DKIM_DB_NAME
          value: "opendkim"
        - name: DKIM_DB_USER
          value: "opendkim"
        - name: DKIM_DB_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: opendkim
              optional: false
        - name: DKIM_SETUP_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: root
              optional: false
        ports:
        - containerPort: 41001
          name: opendkim
