apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: mail
spec:
  selector:
    matchLabels:
      app: mailserver
      tier: postfix
  template:
    metadata:
      labels:
        app: mailserver
        tier: postfix
        logType: postfix
    spec:
      containers:
      - name: postfix
        image: technicalguru/mailserver-postfix:3.5.18.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PF_DB_HOST
          value: "mariadb"
        - name: PF_DB_NAME
          value: "mail"
        - name: PF_DB_USER
          value: "postfix"
        - name: PF_DB_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: postfix
              optional: false
        - name: PF_SETUP_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: root
              optional: false
        - name: PF_MYDOMAIN
          value: "reisman.org"
        - name: PF_MYHOSTNAME
          value: "mail.reisman.org"
        - name: PF_MYORIGIN
          value: "reisman.org"
        - name: PF_AMAVIS_SERVICE_NAME
          # value is complete DNS name: "<service-name>.<namespace-name>.svc.cluster.local"
          value: "amavis.mail.svc.cluster.local"
        - name: PF_AMAVIS_SERVICE_PORT
          value: "10024"
        - name: PF_DKIM_SERVICE_NAME
          value: "opendkim.mail.svc.cluster.local"
        - name: PF_DKIM_SERVICE_PORT
          value: "41001"
        - name: PF_TLS_CERT_FILE
          value: "/var/certificate/tls.crt"
        - name: PF_TLS_KEY_FILE
          value: "/var/certificate/tls.key"
        #- name: PF_TLS_CAFILE
        #  value: "/var/certificate/tls.chain"
        - name: PF_TLS_CAPATH
          value: "/etc/ssl/certs"
        - name: PF_TLS_ADMIN_EMAIL
          value: "postmaster@reisman.org"
        ports:
        - containerPort: 25
          name: smtp
        - containerPort: 110
          name: pop3
        - containerPort: 143
          name: imap
        - containerPort: 587
          name: submission
        - containerPort: 993
          name: imaps
        - containerPort: 995
          name: pop3s
        - containerPort: 10025
          name: checked
        resources: {}
        volumeMounts:
        - name: mailboxes
          mountPath: /var/vmail
        - name: spool
          mountPath: /var/spool/postfix
        - name: certificate
          mountPath: /var/certificate
        - name: "dovecot-nfs"
          mountPath: "/etc/dovecot/conf.d/00-nfs.conf"
          subPath: "00-nfs.conf"
      volumes:
      - name: mailboxes
        persistentVolumeClaim:
          claimName: postfix-mailboxes
      - name: spool
        persistentVolumeClaim:
          claimName: postfix-spool
      - name: certificate
        secret:
          secretName: mail-reisman-org-tls
      - name: dovecot-nfs
        configMap:
          name: dovecot-nfs-config
