apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-reisman-org-tls
  namespace: mail
spec:
  secretName: mail-reisman-org-tls
  dnsNames:
  - mail.reisman.org
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
