apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  namespace: mail
spec:
  selector:
    matchLabels:
      app: mailserver
      tier: roundcube
  template:
    metadata:
      labels:
        app: mailserver
        tier: roundcube
        logType: apache
    spec:
      containers:
      - name: roundcube
        image: technicalguru/mailserver-roundcube:1.6.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: RC_DB_HOST
          value: "mariadb"
        - name: RC_DB_NAME
          value: "roundcube"
        - name: RC_DB_USER
          value: "roundcube"
        - name: RC_DB_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-passwords
              key: roundcube
              optional: false
        - name: RC_DES_KEY
          valueFrom:
            secretKeyRef:
              name: roundcube-des
              key: key
              optional: false
        - name: RC_IMAP_SERVER_NAME
          value: "postfix"
        - name: RC_SMTP_SERVER_NAME
          value: "postfix"
        - name: RC_DEFAULT_DOMAIN
          value: "reisman.org"
        ports:
        - containerPort: 80
          name: http
