apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-nextcloud-privileged
  namespace: default
rules:
- apiGroups:
  - extensions
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use