apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcloud-privileged
  namespace: nextcloud
rules:
- apiGroups:
  - extensions
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcloud-privileged
  namespace: nextcloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextcloud-privileged
subjects:
- kind: ServiceAccount
  name: nextcloud-serviceaccount
  namespace: nextcloud