apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/component: app
    spec:
      initContainers:
      - name: mariadb-isalive
        image: mariadb:latest
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: password
        command:
          - "sh"
          - "-c"
          - until mariadb --host=mariadb.nextcloud.svc.cluster.local --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute="SELECT 1;"; do echo waiting for mariadb; sleep 2; done;
      - name: html-load
        image: alpine:latest
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c" ]
        args: [ "apk update; apk add --upgrade rsync; rsync -av --delete /html-persist/ /html-root && chown -R 33:33 /html-root" ]
        volumeMounts:
          - mountPath: /html-persist
            name: html-persist
          - mountPath: /html-root
            name: html-root 
      containers:
      - name: nextcloud
        image: nextcloud:25.0.0-apache
        imagePullPolicy: IfNotPresent
        env:
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: nextcloud.reisman.org
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        - name: MAIL_FROM_ADDRESS
          value: "nextcloud"
        - name: MAIL_DOMAIN
          value: "reisman.org"
        - name: SMTP_HOST
          value: "mail.reisman.org"
        - name: SMTP_SECURE
          value: "tls"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_AUTHTYPE
          value: "LOGIN"
        - name: SMTP_NAME
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: smtp_username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud
              key: smtp_password
        - name: REDIS_HOST
          value: redis.nextcloud.svc.cluster.local
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
        - name: MYSQL_HOST
          value: mariadb.nextcloud.svc.cluster.local
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: password
        - name: APACHE_DISABLE_REWRITE_IP
          value: "1"
        - name: TRUSTED_PROXIES
          value: "10.0.0.0/8"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status.php
            port: http
            httpHeaders:
            - name: Host
              value: "nextcloud.reisman.org"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status.php
            port: http
            httpHeaders:
            - name: Host
              value: "nextcloud.reisman.org"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources: {}
        volumeMounts:
        - name: html-root
          mountPath: /var/www/html
        - name: data
          mountPath: /var/www/html/data
          subPath: data
        - mountPath: /var/www/html/config
          name: config
          subPath: config
        # - mountPath: /var/www/html/custom_apps
        #   name: customapps
      - name: html-sync
        image: alpine:latest
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c" ]
        args: [ "apk update; apk add --upgrade rsync; while true; do rsync -rlptv --exclude={'config','data'} --delete /html-root/ /html-persist; sleep 60; done" ]
        resources: {}
        volumeMounts:
          - mountPath: /html-persist
            name: html-persist
          - mountPath: /html-root
            name: html-root 
      volumes:
      - name: html-root
        emptyDir: {}
      - name: html-persist
        persistentVolumeClaim:
          claimName: html-pvc
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
      - name: customapps
        persistentVolumeClaim:
          claimName: customapps-pvc
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
      # Will mount configuration files as www-data (id: 33) for nextcloud
      securityContext:
        fsGroup: 33
      serviceAccountName: nextcloud-serviceaccount