apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: nextcloud
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customapps-pvc
  namespace: nextcloud
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: nextcloud
spec:
  storageClassName: "nfs-client-nobackup"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pvc
  namespace: nextcloud
spec:
  storageClassName: "nfs-client-nobackup"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi