apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: nextcloud
spec:
  encryptedData:
    password: AgDkfjsQSH+bW5dlo0h5w22wPjgx02XpiWdC+SzBbe0+98p4i1QXJAaR16HBqZPAX9lTKDK4ckGcBvICyxal0Go+AYGt7TRRbN9XvLRy8Ev6Ys53XdcRJ0bqXKwh5Zupv9R1QD9raE/vk1CEJDTeDuj7og4Hbhb4z7cmeAE8c011UPSGgGhR8lBZpJyXOoUduNifBoidWnJfCK9rLg0n1IhMcBe8oEygXMq8C4dZi7ECWyxUNr3nMnHT6gcg3Tlcb1H8My7IMplok0ZqTU8IY6q0Ov7uuj9g9fPCxd8iaFUeAhfjlXWktYV5fNhjfNvDj/bvn0oyp7UUcKHta+cb7GHheEe5btgAEwYmR/Mw6arxmFMX3hotQoppqk6RQoRvTmO+STIywTFB6KsTauRkKO+1zS7W5RTLlK0IUIgbNCq17TCjCaMe3FUsMJ5b7y2Wf8FNvfZsyFqr/efqDIc3Xmy2kEH0v8KOhXQTDQ753KU1GFrPId3g6ATav4o6rneYUKlgJurwp4HpS3Nq+4RE7d5edeaneuTSSK+cEs4pMO8CKelgl1NQz6teohgW5y6PN09ThS3c8Bsf6135+WgAXqt+Kn4mIOBVMhP5S48CJSpFFlkhdKpLEWW+HSF/oHxAsbcKjAAUfH5dGWluPWGjxK4WM4bmWoxEDV3/ujd4JxiDvmMQO3vaTbOJPxIcbGUXAHK4MZ7VqI6IzbvAN1jJSnrsYf52xLKfGNlUqzI38JRCaZ+jUuTB4Acj4l+r+aDz9RGN+q0rCBIX5qXZiSk=
  template:
    metadata:
      name: redis
      namespace: nextcloud
    type: Opaque